version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 15.0.0
  - dependency-name: "@nestjs/schematics"
    versions:
    - 7.3.0
  - dependency-name: typescript
    versions:
    - 3.9.8
  - dependency-name: "@nestjs/testing"
    versions:
    - 7.6.9
